### ISSUE TITLE
issue with dm-do-adapter

### ISSUE THREAD

**Issue by solnic** [datamapper/dm-do-adapter#5]
the error is something about a badly formatted url

```
Malformed URI: java.net.URISyntaxException: Expected scheme-specific part at index 7: sqlite: 
from /opt/local/share/java/jruby/lib/ruby/gems/1.8/gems/data_objects-0.10.2/lib/data_objects/connection.rb:76:in `new'
from /opt/local/share/java/jruby/lib/ruby/gems/1.8/gems/data_objects-0.10.2/lib/data_objects/pooling.rb:177:in `new'
from /opt/local/share/java/jruby/lib/ruby/gems/1.8/gems/data_objects-0.10.2/lib/data_objects/pooling.rb:172:in `new'
from /opt/local/share/java/jruby/lib/ruby/gems/1.8/gems/data_objects-0.10.2/lib/data_objects/pooling.rb:119:in `new'
from /opt/local/share/java/jruby/lib/ruby/gems/1.8/gems/data_objects-0.10.2/lib/data_objects/connection.rb:65:in `new'
from /opt/local/share/java/jruby/lib/ruby/gems/1.8/gems/dm-do-adapter-1.0.2/lib/dm-do-adapter/adapter.rb:235:in `open_connection'
from /opt/local/share/java/jruby/lib/ruby/gems/1.8/gems/dm-transactions-1.0.2/lib/dm-transactions/adapters/dm-do-adapter.rb:65:in `open_connection'
from /opt/local/share/java/jruby/lib/ruby/gems/1.8/gems/dm-do-adapter-1.0.2/lib/dm-do-adapter/adapter.rb:260:in `with_connection'
from /opt/local/share/java/jruby/lib/ruby/gems/1.8/gems/dm-do-adapter-1.0.2/lib/dm-do-adapter/adapter.rb:138:in `read'
from /opt/local/share/java/jruby/lib/ruby/gems/1.8/gems/dm-core-1.0.2/lib/dm-core/repository.rb:162:in `read'
from /opt/local/share/java/jruby/lib/ruby/gems/1.8/gems/dm-core-1.0.2/lib/dm-core/model.rb:379:in `first'
from /opt/local/share/java/jruby/lib/ruby/gems/1.8/gems/dm-core-1.0.2/lib/dm-core/model.rb:446:in `first_or_create'
from /Users/path/Projects/pg/pgservice/app/handlers/create_user_handler.rb:9:in ... (user code)
```

---

Created by **pathsny (at gmail)** - 2010-09-09 17:38:26 UTC

Original Lighthouse ticket: [http://datamapper.lighthouseapp.com/projects/20609/tickets/1400](http://datamapper.lighthouseapp.com/projects/20609/tickets/1400)

**Comment by solnic** [comment]
A bit more information please! Ideally, a standalone script to reproduce. This stracktrace leaves us with guesswork only, which isn&rsquo;t something very pleasant. Thx!

 by Martin Gamsjaeger (snusnu)
